# Generated by Django 5.0.7 on 2024-08-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_category_options_alter_studentinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='profile_picture',
        ),
    ]
